/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javacalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

    boolean flag = false;
    String firstNumber = "";
    String secondNumber = "";
    char operator = ' ';
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_3 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        button_plus_minus = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        dot_button = new javax.swing.JButton();
        product_button = new javax.swing.JButton();
        minus_button = new javax.swing.JButton();
        plus_button = new javax.swing.JButton();
        equal_button = new javax.swing.JButton();
        divide_button = new javax.swing.JButton();
        result_field = new javax.swing.JTextField();
        button_10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaCalculator");
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        button_3.setBackground(new java.awt.Color(0, 0, 0));
        button_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_3.setForeground(new java.awt.Color(255, 255, 255));
        button_3.setText("3");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_1.setBackground(new java.awt.Color(0, 0, 0));
        button_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_1.setForeground(new java.awt.Color(255, 255, 255));
        button_1.setText("1");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setBackground(new java.awt.Color(0, 0, 0));
        button_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_2.setForeground(new java.awt.Color(255, 255, 255));
        button_2.setText("2");
        button_2.setToolTipText("");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_4.setBackground(new java.awt.Color(0, 0, 0));
        button_4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_4.setForeground(new java.awt.Color(255, 255, 255));
        button_4.setText("4");
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        button_5.setBackground(new java.awt.Color(0, 0, 0));
        button_5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_5.setForeground(new java.awt.Color(255, 255, 255));
        button_5.setText("5");
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_6.setBackground(new java.awt.Color(0, 0, 0));
        button_6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_6.setForeground(new java.awt.Color(255, 255, 255));
        button_6.setText("6");
        button_6.setToolTipText("");
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_8.setBackground(new java.awt.Color(0, 0, 0));
        button_8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_8.setForeground(new java.awt.Color(255, 255, 255));
        button_8.setText("8");
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_7.setBackground(new java.awt.Color(0, 0, 0));
        button_7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_7.setForeground(new java.awt.Color(255, 255, 255));
        button_7.setText("7");
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_9.setBackground(new java.awt.Color(0, 0, 0));
        button_9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_9.setForeground(new java.awt.Color(255, 255, 255));
        button_9.setText("9");
        button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_9ActionPerformed(evt);
            }
        });

        button_plus_minus.setBackground(new java.awt.Color(0, 0, 0));
        button_plus_minus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_plus_minus.setForeground(new java.awt.Color(255, 255, 255));
        button_plus_minus.setText("-/+");
        button_plus_minus.setEnabled(false);
        button_plus_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plus_minusActionPerformed(evt);
            }
        });

        button_0.setBackground(new java.awt.Color(0, 0, 0));
        button_0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_0.setForeground(new java.awt.Color(255, 255, 255));
        button_0.setText("0");
        button_0.setToolTipText("");
        button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_0ActionPerformed(evt);
            }
        });

        dot_button.setBackground(new java.awt.Color(0, 0, 0));
        dot_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dot_button.setForeground(new java.awt.Color(255, 255, 255));
        dot_button.setText(".");
        dot_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dot_buttonActionPerformed(evt);
            }
        });

        product_button.setBackground(new java.awt.Color(0, 0, 0));
        product_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        product_button.setForeground(new java.awt.Color(255, 255, 255));
        product_button.setText("*");
        product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_buttonActionPerformed(evt);
            }
        });

        minus_button.setBackground(new java.awt.Color(0, 0, 0));
        minus_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        minus_button.setForeground(new java.awt.Color(255, 255, 255));
        minus_button.setText("-");
        minus_button.setToolTipText("");
        minus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minus_buttonActionPerformed(evt);
            }
        });

        plus_button.setBackground(new java.awt.Color(0, 0, 0));
        plus_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plus_button.setForeground(new java.awt.Color(255, 255, 255));
        plus_button.setText("+");
        plus_button.setToolTipText("");
        plus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_buttonActionPerformed(evt);
            }
        });

        equal_button.setBackground(new java.awt.Color(0, 0, 0));
        equal_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        equal_button.setForeground(new java.awt.Color(255, 255, 255));
        equal_button.setText("=");
        equal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equal_buttonActionPerformed(evt);
            }
        });

        divide_button.setBackground(new java.awt.Color(0, 0, 0));
        divide_button.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divide_button.setForeground(new java.awt.Color(255, 255, 255));
        divide_button.setText("/");
        divide_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_buttonActionPerformed(evt);
            }
        });

        result_field.setBackground(new java.awt.Color(204, 204, 204));
        result_field.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        result_field.setText("0");
        result_field.setToolTipText("");
        result_field.setBorder(null);
        result_field.setCaretColor(new java.awt.Color(204, 204, 204));
        result_field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        result_field.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                result_fieldInputMethodTextChanged(evt);
            }
        });
        result_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                result_fieldActionPerformed(evt);
            }
        });
        result_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                result_fieldKeyTyped(evt);
            }
        });

        button_10.setBackground(new java.awt.Color(0, 0, 0));
        button_10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_10.setForeground(new java.awt.Color(255, 255, 255));
        button_10.setText("C");
        button_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_plus_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dot_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button_10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(product_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(result_field, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divide_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(product_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(equal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_plus_minus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void writeNumber(String number) {  
        if (!"0".equals(result_field.getText())){
            if (!this.flag) {
                if ("0".equals(this.firstNumber) & "0".equals(number)) {
                    result_field.setText(number);
                } else {              
                  this.firstNumber += number;
                  result_field.setText(result_field.getText() + number);
                }
            } else {
                 if ("0".equals(this.secondNumber) & "0".equals(number)) {
                     result_field.setText(this.firstNumber + this.operator + number);
                 } else {
                    this.secondNumber += number;
                    result_field.setText(result_field.getText() + number);  
                 }    
            }                   
        } else {
            result_field.setText("");       
            writeNumber(number);
        }
    }
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    void writeDecimal() {    
        if (this.operator == ' ') {
            if (!this.firstNumber.contains(".") && this.firstNumber.length() > 0) {
                this.firstNumber += '.';
                this.addDot();
            }
        } else {
            if (!this.secondNumber.contains(".") && this.secondNumber.length() > 0) {
                this.secondNumber += '.';
                this.addDot();
            }
        }
    }
      
    void clearInput() {  
        this.operator = ' ';
        this.firstNumber = "";
        this.secondNumber = "";
        this.flag = false;
        result_field.setText("");
    }
    
    void writeOperator(char requestedOperator) {      
        this.operator = requestedOperator;
        if (!this.flag && result_field.getText().length() != 0) {
            result_field.setText(result_field.getText() + operator);
            this.flag = true;
        } else {
            this.operator = requestedOperator;
            result_field.setText( result_field.getText().substring(0, result_field.getText().length() - 1));        
            result_field.setText(result_field.getText() + operator);
            this.flag = true;
        }
    }
    
    void resetNumber() { //may be used in future to do to show history      
        this.flag = false;
        this.firstNumber = result_field.getText();
        this.secondNumber = "";
    }
    
    void equal() {
        result_field.setText("");
        switch (this.operator) {
            case '+':           
                result_field.setText(String.valueOf(Float.parseFloat(firstNumber) + Float.parseFloat(secondNumber)) );
                this.resetNumber();              
                break;
            case '-':
                result_field.setText(String.valueOf(Float.parseFloat(firstNumber) - Float.parseFloat(secondNumber)) );
                this.resetNumber();
                break;
            case '*':
                result_field.setText(String.valueOf(Float.parseFloat(firstNumber) * Float.parseFloat(secondNumber)) );
               this.resetNumber();
                break;
            case '/':
                if ("0".equals(this.secondNumber)) {
                    result_field.setText("Error");
                    //this.clearInput();
                } else {
                    result_field.setText(String.valueOf(Float.parseFloat(firstNumber) / Float.parseFloat(secondNumber)) );
                  this.resetNumber();
                }
                break;
        }
        this.operator = ' ';
    }
    
    void addDot() {    
        result_field.setText(result_field.getText() + '.');
    }

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
       writeNumber("3");
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
       writeNumber("1");          
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        writeNumber("2");      
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
        writeNumber("4");       
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
        writeNumber("5");     
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
        writeNumber("6");
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
        writeNumber("8");
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
        writeNumber("7");
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_9ActionPerformed
        writeNumber("9");
    }//GEN-LAST:event_button_9ActionPerformed

    private void button_plus_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plus_minusActionPerformed
        
    }//GEN-LAST:event_button_plus_minusActionPerformed

    private void button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_0ActionPerformed
        writeNumber("0");
    }//GEN-LAST:event_button_0ActionPerformed

    private void dot_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dot_buttonActionPerformed
        writeDecimal();
    }//GEN-LAST:event_dot_buttonActionPerformed

    private void product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_buttonActionPerformed
        writeOperator('*');
    }//GEN-LAST:event_product_buttonActionPerformed

    private void minus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus_buttonActionPerformed
       writeOperator('-');
    }//GEN-LAST:event_minus_buttonActionPerformed

    private void plus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_buttonActionPerformed
        writeOperator('+');
    }//GEN-LAST:event_plus_buttonActionPerformed

    private void equal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equal_buttonActionPerformed
       equal();
    }//GEN-LAST:event_equal_buttonActionPerformed

    private void divide_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_buttonActionPerformed
       writeOperator('/');
    }//GEN-LAST:event_divide_buttonActionPerformed

    private void result_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_result_fieldKeyTyped
       char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }                   
    }//GEN-LAST:event_result_fieldKeyTyped

    private void button_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_10ActionPerformed
        clearInput();   
    }//GEN-LAST:event_button_10ActionPerformed

    private void result_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_result_fieldActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       result_field.setText(firstNumber);
    }//GEN-LAST:event_formWindowOpened

    private void result_fieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_result_fieldInputMethodTextChanged
      
    }//GEN-LAST:event_result_fieldInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_10;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_plus_minus;
    private javax.swing.JButton divide_button;
    private javax.swing.JButton dot_button;
    private javax.swing.JButton equal_button;
    private javax.swing.JButton minus_button;
    private javax.swing.JButton plus_button;
    private javax.swing.JButton product_button;
    private javax.swing.JTextField result_field;
    // End of variables declaration//GEN-END:variables
}
